/* Контактный лист: node tools/mannequin/sheet.mjs --ids a,b --t 0,0.5,1 --cams angle,side,front --out file.png [--cols 3] */
import fs from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),require=createRequire(path.join(root,'package.json'));
const {build}=require('esbuild'),{chromium}=require('playwright');
const arg=(k,d)=>{const i=process.argv.indexOf(k);return i>0?process.argv[i+1]:d;};
const ids=arg('--ids','').split(',').filter(Boolean),ts=arg('--t','0,0.5,1').split(',').map(Number),cams=arg('--cams','angle,side,front').split(','),out=arg('--out','qa/sheet.png'),cols=+arg('--cols',String(cams.length)),w=+arg('--w','380'),h=+arg('--h','300');
const {bakeAll}=require('./tools/mannequin/author.js'.replace('./',root+'/'));
const entries=bakeAll({only:ids.length?ids:null});
const list=ids.length?ids:Object.keys(entries);
const lab=path.join(root,'tools/mannequin/.lab',String(process.pid));await fs.mkdir(lab,{recursive:true});
await build({entryPoints:[path.join(root,'tools/mannequin/lab/entry.mjs')],outfile:path.join(lab,'lab.js'),bundle:true,format:'iife',target:['es2020'],logLevel:'error'});
await fs.writeFile(path.join(lab,'index.html'),`<!doctype html><meta charset="utf-8"><body style="margin:0;background:#000"><script src="${root}/src/js/09bm-mannequin.js"></script><script src="${root}/src/js/09bn-equipment.js"></script>${(await fs.readdir(path.join(root,'src/js'))).filter(f=>/^09bo.*\.js$/.test(f)).sort().map(f=>`<script src="${root}/src/js/${f}"></script>`).join('')}<script src="lab.js"></script>`);
const browser=await chromium.launch({args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.goto('file://'+path.join(lab,'index.html'));
const specs=[];for(const id of list)for(const t of ts)for(const cam of cams)specs.push({id,t,cam});
const url=await page.evaluate(([specs,entries,o])=>Lab.sheet(specs,entries,o),[specs,entries,{w,h,cols,title:arg('--title',''),has:arg('--has',null)}]);
await fs.mkdir(path.dirname(path.resolve(root,out)),{recursive:true});
await fs.writeFile(path.resolve(root,out),Buffer.from(url.split(',')[1],'base64'));
if(errors.length)console.log('Ошибки страницы:',errors.slice(0,5));console.log(out);await browser.close();await fs.rm(lab,{recursive:true,force:true});
